### ISSUE TITLE
Early temporal dynamics of cellular responses to SARS-CoV-2

### ISSUE THREAD

**Issue by danieljrichard** [urmi-21/COVID-19-RNA-Seq-datasets#12]
Hello,
I believe the datasets for the study by Banerjee et al have been made available on GEO datasets (http://www.ncbi.nlm.nih.gov/geo/query/acc.cgi?acc=GSE151513) - just to update the excellent aggregation of datasets here.

**Comment by urmi-21** [comment]
I will update it. Thank you
